### ISSUE TITLE
Node error during build

### ISSUE THREAD

**Issue by kirill-konshin** [balena-io/deploy-to-balena-action#199]
I am using Balena GitHub action:

```yml
      - name: Balena
        uses: balena-io/deploy-to-balena-action@master
        if: github.ref_type == 'tag' || github.ref_name == 'master'
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: ${{ env.GITHUB_REF_TYPE == 'tag' && 'xxx-beta' || 'xxx-staging' }}
```

It produces following log:

```
Run balena-io/deploy-to-balena-action@master
/usr/bin/docker run --name xxx --label xxx --workdir /github/workspace --rm -e "INPUT_BALENA_TOKEN" -e "INPUT_FLEET" -e "INPUT_GITHUB_TOKEN" -e "INPUT_ENVIRONMENT" -e "INPUT_VERSIONBOT" -e "INPUT_FINALIZE" -e "INPUT_CREATE_TAG" -e "INPUT_CREATE_REF" -e "INPUT_CACHE" -e "INPUT_SOURCE" -e "INPUT_LAYER_CACHE" -e "INPUT_REGISTRY_SECRETS" -e "BALENA_TOKEN" -e "BALENA_URL" -e "REGISTRY_SECRETS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/sputnik-1/sputnik-1":"/github/workspace" xxx:xxx
 _            _
| |__   __ _ | |  ____  _ __    __ _
| '_ \ / _` || | / __ \| '_ \  / _` |
| |_) | (_) || ||  ___/| | | || (_) |
|_.__/ \__,_||_| \____/|_| |_| \__,_|


Logging in to balena-cloud.com
Successfully logged in as: xxx

Find out about the available commands by running:

  $ balena help

For further help or support, visit:
https://www.balena.io/docs/reference/balena-cli/#support-faq-and-troubleshooting

git version 2.30.2
Initializing SDK for [https://api.balena-cloud.com)](https://api.balena-cloud.com%29/)
Checking if a release has already been built.
Did not find existing release so building a new one.
Error: No such file or directory: /github/workspace/node_modules/cpu-features/build/node_gyp_bins/python3
```
