### ISSUE TITLE
Builds fail when not from default branch.

### ISSUE THREAD

**Issue by kwaremburg360** [balena-io/deploy-to-balena-action#258]
We've discovered that builds fail if you try to trigger it not from the default branch of the repo.  We found the check and can fork and then remove it but we'd like to understand why this check was imposed in the first place. 

We'd like to be able to build from develop or master branches.

**Comment by stevedh** [comment]
Did you get it working off a different branch?  I would also like to know the reason for this limitation.

**Comment by kwaremburg360** [comment]
You can actually override the default branch with one of the inputs to the GHA.

```
      - uses: balena-io/deploy-to-balena-action@master
        id: build
        with:
          default_branch: ${{ github.ref_name }}
```

See the README.md for more details.
https://github.com/balena-io/deploy-to-balena-action/blob/master/README.md
