### ISSUE TITLE
Publish action image to public registry

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/deploy-to-balena-action#27]
If we publish a built image of the action then we can reference that in workflows which would save the entire build time. This will speed up the action significantly.

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-a-docker-hub-action

**Comment by klutchell** [comment]
We should attempt to use the balena registry and an open fleet for this once we add support for vanity image names.
More to come.

**Comment by 20k-ultra** [comment]
Can you elaborate on the open fleet part ? I like the idea of using balena registry as long as the image path is recognizable and not random strings. People have to add this url to their workflow so if it's random strings then the UX seems worse compared to a recognizable location.

**Comment by klutchell** [comment]
https://jel.ly.fish/milestone-block-images-balena-registry-4ef9934

It's a blocks milestone for now, but it impacts any project we would normally put in DH.

> We want to host balenaBlock images in the balena registry, but have human-readable references for users to add to their docker-compose file.

**tl;dr** we are looking at adding a pre-pull hook to our registry to translate names to full image paths.

**Comment by klutchell** [comment]
Now that the proxy has shipped we should push this project to a fleet (via deploy-to-balena action of course) and have users pull the image at runtime to save compiling.

```
      - uses: bh.cr/balena/deploy-to-balena@v0.9.0
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: my_org/sample_fleet
```
