### ISSUE TITLE
Input does not meet YAML 1.2 "Core Schema" specification: create_ref

### ISSUE THREAD

**Issue by maggie0002** [balena-io/deploy-to-balena-action#77]
Started getting this error today:

```
Input does not meet YAML 1.2 "Core Schema" specification: create_ref
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

Prevents the workflow from completing successfully. 
```

[Info]        Build finished in 6 minutes, 45 seconds
1749

1750

1751
			    \
1752
			     \       .,-.@
1753
			      \\   .^xxx-
1754
			       \\,xxxxx;
1755
			        >  xxx/
1756
			    _.-(6'  xx
1757
			   (=___._/` \
1758
			        )  \ |
1759
			       /   / |
1760
			      /    > /
1761
			     j    < _\
1762
			 _.-' :      ``.
1763
			 \ r=._\        `.
1764
			<`\\_  \         .`-.
1765
			 \ r-7  `-. ._  ' .  `\
1766
			  \`,      `-.`7  7)   )
1767
			   \/         \|  \'  / `-._
1768
			              ||    .'
1769
			               \\  (
1770
			                >\  >
1771
			            ,.-' >.'
1772
			           <.'_.'
1773
			             <'
1774
			
1775

1776
Build process exit
1777

1778

1779
Error: Input does not meet YAML 1.2 "Core Schema" specification: create_ref
1780
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

```
      - name: Deploy aarch64 to development
        uses: balena-io/deploy-to-balena-action@master
        id: build-dev-aarch64
        with:
          balena_token: ${{ secrets.BALENA_API_TOKEN }}
          fleet: myfleet/myfleet
```
